export {default as ViewYourJobs} from './ViewYourJobs';
export {default as HomeLayout} from './HomeLayout';
export {default as About} from './About';
export {default as Admin} from './Admin';
export {default as AllJobs} from './AllJobs';
export {default as Apply} from './Apply';
export {default as Error} from './Error';
export {default as EditJob} from './EditJob';
export {default as Register} from './Register';
export {default as Login} from './Login';
export {default as Profile} from './Profile';
export {default as Landing} from './Landing';
export {default as Contact} from './Contact';
export {default as Application} from './Application'
export {default as ResumeModal} from './ResumeModal'
export {default as PopularCompanies} from './PopularCompanies'
export {default as Myjobs} from './Myjobs'
export {default as PopularCategory} from './PopularCategory'
export {default as JobDetails} from './JobDetails'
export {default as Howitworks} from './Howitworks'
export {default as Myapplication} from './Myapplication'
export {default as PostJob} from './PostJob'
export {default as PorfileEdit} from './PorfileEdit'